apiVersion: v1
kind: Secret
metadata:
  name: env-secrets-stag
  namespace: argocd
type: Opaque
stringData:
  DATABASE_URL: postgresql://user:pass@db.stag.svc.cluster.local:5432/appdb
  REDIS_URL: redis://redis.stag.svc.cluster.local:6379
  API_KEY: stag-placeholder-key
