apiVersion: v1
kind: Secret
metadata:
  name: shared-docker-registry-secret
  namespace: default  
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "docker.io": {
          "username": "{{ .Values.dockerRegistry.username }}",
          "password": "{{ .Values.dockerRegistry.token }}",
          "email": "{{ .Values.dockerRegistry.email }}",
          "auth": "{{ printf "%s:%s" .Values.dockerRegistry.username .Values.dockerRegistry.token | b64enc }}"
        }
      }
    }
---
# Copy secret to other namespaces if needed
apiVersion: v1
kind: Secret
metadata:
  name: shared-docker-registry-secret
  namespace: verigen-chat
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "docker.io": {
          "username": "{{ .Values.dockerRegistry.username }}",
          "password": "{{ .Values.dockerRegistry.token }}",
          "email": "{{ .Values.dockerRegistry.email }}",
          "auth": "{{ printf "%s:%s" .Values.dockerRegistry.username .Values.dockerRegistry.token | b64enc }}"
        }
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: shared-docker-registry-secret
  namespace: verigen-rag
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "docker.io": {
          "username": "{{ .Values.dockerRegistry.username }}",
          "password": "{{ .Values.dockerRegistry.token }}",
          "email": "{{ .Values.dockerRegistry.email }}",
          "auth": "{{ printf "%s:%s" .Values.dockerRegistry.username .Values.dockerRegistry.token | b64enc }}"
        }
      }
    }

---
apiVersion: v1
kind: Secret
metadata:
  name: shared-docker-registry-secret
  namespace: verigen-sso
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "docker.io": {
          "username": "{{ .Values.dockerRegistry.username }}",
          "password": "{{ .Values.dockerRegistry.token }}",
          "email": "{{ .Values.dockerRegistry.email }}",
          "auth": "{{ printf "%s:%s" .Values.dockerRegistry.username .Values.dockerRegistry.token | b64enc }}"
        }
      }
    }