apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount.backend }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
        - name: backend
          image: {{ .Values.image.backend }}
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-secrets
            - secretRef:
                name: {{ .Release.Name }}-aws-credentials
            - configMapRef:
                name: {{ .Release.Name }}-s3-config
          volumeMounts:
            - name: uploads
              mountPath: /app/uploads
      volumes:
        - name: uploads
          emptyDir: {}
          resources:
            {{- toYaml .Values.resources.backend | nindent 12 }}