apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount.backend }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
    spec:
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
        - name: backend
          image: {{ .Values.image.backend }}
          ports:
            - containerPort: {{ .Values.service.backend.targetPort }}
          command:
            - bash
            - -c
            - |
              python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.username }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password }}
            - name: POSTGRES_HOST
              value: {{ .Release.Name }}-postgres
            - name: POSTGRES_PORT
              value: "5432"
          volumeMounts:
            - name: app-volume
              mountPath: /app
      restartPolicy: OnFailure
      volumes:
        - name: app-volume
          emptyDir: {}
      dependsOn:
        - {{ .Release.Name }}-postgres
