apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount.frontend }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-frontend
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
        - name: frontend
          image: {{ .Values.image.frontend }}
          ports:
            - containerPort: 80
          env:
            - name: VITE_SERVICE_ENDPOINT
              value: "http://{{ .Release.Name }}-backend:8000/"
            - name: VITE_SSO_ENDPOINT
              value: "{{ .Values.env.frontend.ssoEndpoint }}"
            - name: VITE_DOMAIN_SSO
              value: "{{ .Values.env.frontend.domainSSO }}"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"