{{- if or .Values.components.frontend.enabled .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.components.frontend.replicas | default .Values.replicaCount.frontend }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-frontend
    spec:
      restartPolicy: Always
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      containers:
        - name: frontend
          image: {{ .Values.components.frontend.image | default .Values.image.frontend }}
          ports:
            - containerPort: {{ .Values.components.frontend.targetPort | default .Values.service.frontend.targetPort }}
          {{- if or .Values.components.frontend.env .Values.frontend.env }}
          env:
            {{- range $key, $value := (.Values.components.frontend.env | default .Values.frontend.env) }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          {{- if or .Values.components.frontend.envFrom .Values.frontend.envFrom }}
          envFrom:
            {{- range (.Values.components.frontend.envFrom | default .Values.frontend.envFrom) }}
            {{- if .secretRef }}
            - secretRef:
                name: {{ .secretRef.name }}
            {{- end }}
            {{- if .configMapRef }}
            - configMapRef:
                name: {{ .configMapRef.name }}
            {{- end }}
            {{- end }}
          {{- end }}
          {{- if or .Values.components.frontend.resources .Values.resources.frontend }}
          resources:
            {{- toYaml (.Values.components.frontend.resources | default .Values.resources.frontend) | nindent 12 }}
          {{- end }}
{{- end }}