{{- range $name, $config := .Values.containers }}
{{- if $config.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-{{ $name }}
  namespace: {{ $.Values.namespace }}
spec:
  replicas: {{ $config.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ $.Release.Name }}-{{ $name }}
  template:
    metadata:
      labels:
        app: {{ $.Release.Name }}-{{ $name }}
    spec:
      {{- if $.Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ $.Values.imagePullSecrets }}
      {{- end }}
      containers:
        - name: {{ $name }}
          image: {{ $config.image }}
          imagePullPolicy: {{ $config.imagePullPolicy | default "Always" }}
          {{- if $config.containerPort }}
          ports:
            - containerPort: {{ $config.containerPort }}
          {{- end }}
          {{- if $config.command }}
          command:
            {{- range $config.command }}
            - {{ . | quote }}
            {{- end }}
          {{- end }}
          {{- if $config.args }}
          args:
            {{- range $config.args }}
            - {{ . | quote }}
            {{- end }}
          {{- end }}
          {{- if $config.env }}
          env:
            {{- if kindIs "slice" $config.env }}
            {{- toYaml $config.env | nindent 12 }}
            {{- else }}
            {{- range $key, $value := $config.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
          {{- end }}
          {{- if $config.envFrom }}
          envFrom:
            {{- range $config.envFrom }}
            {{- if .secretRef }}
            - secretRef:
                name: {{ .secretRef.name }}
            {{- end }}
            {{- if .configMapRef }}
            - configMapRef:
                name: {{ .configMapRef.name }}
            {{- end }}
            {{- end }}
          {{- end }}
          {{- if $config.volumeMounts }}
          volumeMounts:
            {{- range $config.volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              {{- if .subPath }}
              subPath: {{ .subPath }}
              {{- end }}
            {{- end }}
          {{- end }}
          {{- if $config.resources }}
          resources:
            {{- toYaml $config.resources | nindent 12 }}
          {{- end }}
      {{- if $config.volumes }}
      volumes:
        {{- range $config.volumes }}
        - name: {{ .name }}
          {{- if .emptyDir }}
          emptyDir: {}
          {{- end }}
          {{- if .persistentVolumeClaim }}
          persistentVolumeClaim:
            claimName: {{ .persistentVolumeClaim.claimName }}
          {{- end }}
          {{- if .configMap }}
          configMap:
            name: {{ .configMap.name }}
          {{- end }}
          {{- if .secret }}
          secret:
            secretName: {{ .secret.secretName }}
          {{- end }}
        {{- end }}
      {{- end }}
{{- end }}
{{- end }}
