apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "docker.io": {
          "username": "{{ .Values.dockerRegistry.username }}",
          "password": "{{ .Values.dockerRegistry.token }}",
          "email": "{{ .Values.dockerRegistry.email }}",
          "auth": "{{ printf "%s:%s" .Values.dockerRegistry.username .Values.dockerRegistry.token | b64enc }}"
        }
      }
    }
