{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    {{- if .Values.ingress.host }}
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          {{- if or .Values.backend.enabled (and .Values.containers (or .Values.containers.chat-backend.enabled .Values.containers.rag-backend.enabled)) }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-backend
                port:
                  number: {{ if .Values.service.backend.port }}{{ .Values.service.backend.port }}{{ else }}8000{{ end }}
          {{- end }}
          {{- if or .Values.frontend.enabled (and .Values.containers (or .Values.containers.chat-frontend.enabled .Values.containers.rag-frontend.enabled)) }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-frontend
                port:
                  number: {{ if .Values.service.frontend.port }}{{ .Values.service.frontend.port }}{{ else if .Values.containers.chat-frontend.service.port }}{{ .Values.containers.chat-frontend.service.port }}{{ else if .Values.containers.rag-frontend.service.port }}{{ .Values.containers.rag-frontend.service.port }}{{ else }}80{{ end }}
          {{- end }}
    {{- end }}
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $.Release.Name }}-frontend
                port:
                  number: {{ $.Values.service.frontend.port }}
        {{- end }}
    {{- end }}
{{- end }}