{{- if .Values.mariadb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mariadb
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mariadb
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mariadb
    spec:
      containers:
        - name: mariadb
          image: {{ .Values.mariadb.image }}
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mariadb.rootPassword }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mariadb.database }}
            - name: MYSQL_USER
              value: {{ .Values.mariadb.username }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mariadb.password }}
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
          resources:
            {{- toYaml .Values.mariadb.resources | nindent 12 }}
      volumes:
        - name: mariadb-data
          {{- if .Values.mariadb.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-mariadb-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mariadb
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-mariadb
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
{{- if .Values.mariadb.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mariadb-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mariadb.persistence.size }}
{{- end }}
{{- end }}