{{- if .Values.qdrant.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-qdrant
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-qdrant
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-qdrant
    spec:
      containers:
        - name: qdrant
          image: {{ .Values.qdrant.image }}
          ports:
            - containerPort: 6333
            - containerPort: 6334
          volumeMounts:
            - name: qdrant-storage
              mountPath: /qdrant/storage
          resources:
            {{- toYaml .Values.qdrant.resources | nindent 12 }}
      volumes:
        - name: qdrant-storage
          {{- if .Values.qdrant.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-qdrant-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-qdrant
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-qdrant
  ports:
    - name: http
      protocol: TCP
      port: 6333
      targetPort: 6333
    - name: grpc
      protocol: TCP
      port: 6334
      targetPort: 6334
  type: ClusterIP
{{- if .Values.qdrant.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-qdrant-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.qdrant.persistence.size }}
{{- end }}
{{- end }}