{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  {{- if .Values.postgres.enabled }}
  postgres-url: "postgresql://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@{{ .Release.Name }}-postgres:5432/{{ .Values.postgres.database }}"
  postgres-username: {{ .Values.postgres.username | quote }}
  postgres-password: {{ .Values.postgres.password | quote }}
  {{- end }}
  {{- if .Values.mongo.enabled }}
  mongo-url: "mongodb://{{ .Values.mongo.username }}:{{ .Values.mongo.password }}@{{ .Release.Name }}-mongo:27017/{{ .Values.mongo.database }}"
  mongo-username: {{ .Values.mongo.username | quote }}
  mongo-password: {{ .Values.mongo.password | quote }}
  {{- end }}
  {{- if .Values.redis.enabled }}
  redis-url: "redis://{{ .Release.Name }}-redis:6379"
  {{- end }}
  {{- if .Values.qdrant.enabled }}
  qdrant-url: "http://{{ .Release.Name }}-qdrant:6333"
  {{- end }}
  {{- if .Values.mariadb.enabled }}
  MYSQL_HOST: {{ .Release.Name }}-mariadb
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: {{ .Values.mariadb.database | quote }}
  MYSQL_USER: {{ .Values.mariadb.username | quote }}
  MYSQL_PASSWORD: {{ .Values.mariadb.password | quote }}
  {{- end }}
  {{- if .Values.minio.enabled }}
  MINIO_ENDPOINT: {{ .Release.Name }}-minio:9000
  MINIO_ACCESS_KEY: {{ .Values.minio.accessKey | quote }}
  MINIO_SECRET_KEY: {{ .Values.minio.secretKey | quote }}
  {{- end }}
  {{- if .Values.secrets.jwtSecret }}
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.openaiKey }}
  openai-key: {{ .Values.secrets.openaiKey | quote }}
  {{- end }}
{{- end }}