{{- range $name, $config := .Values.containers }}
{{- if and $config.enabled $config.service $config.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ $name }}
  namespace: {{ $.Values.namespace }}
spec:
  selector:
    app: {{ $.Release.Name }}-{{ $name }}
  ports:
    - protocol: TCP
      port: {{ $config.service.port }}
      targetPort: {{ $config.service.targetPort | default $config.containerPort }}
  type: {{ $config.service.type | default "ClusterIP" }}
{{- end }}
{{- end }}
