apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vsvn-HoangTC/argocd-apps.git
    targetRevision: main
    path: apps-of-apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vsvn-HoangTC/argocd-apps.git
    targetRevision: main
    path: apps_dev
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-stag
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vsvn-HoangTC/argocd-apps.git
    targetRevision: main
    path: apps_stag
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
