# Template mặc định cho ArgoCD Application
appName: ""
argoNamespace: "argocd"
project: "default"

source:
  repoURL: ""
  targetRevision: "HEAD"
  path: ""
  helm:
    valueFiles:
      - values.yaml

destination:
  server: "https://kubernetes.default.svc"
  namespace: ""

syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true

# Default values for templates
frontend:
  enabled: true

backend:
  enabled: true

worker:
  enabled: true

namespace: "default"

service:
  frontend:
    type: ClusterIP
    port: 80
    targetPort: 80
  backend:
    type: ClusterIP
    port: 8000
    targetPort: 8000